# Generated by Django 2.1.2 on 2018-11-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Something about yourself', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.CharField(default='YYYY-MM-DD', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='Town/City', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='?', max_length=100),
        ),
    ]
