# Generated by Django 2.1.2 on 2018-11-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181112_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='hobbyName', max_length=100)),
                ('description', models.TextField(default='hobbyDesc', max_length=100)),
                ('profiles', models.ManyToManyField(to='users.Profile')),
            ],
        ),
    ]
