# Generated by Django 2.1.2 on 2018-11-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_hobby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='profiles',
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(to='users.Hobby'),
        ),
    ]
