# Generated by Django 2.1.2 on 2018-11-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181112_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='?', max_length=1),
        ),
    ]
