# Generated by Django 2.1.2 on 2018-11-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181112_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.CharField(default='YYYY-MM-DD', max_length=10),
        ),
    ]
