# Generated by Django 2.1 on 2018-11-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_adjectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hotness',
            field=models.ManyToManyField(blank=True, to='users.Profile'),
        ),
    ]
