# Generated by Django 2.1 on 2018-11-15 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_profile_hotness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='hotness',
            new_name='heat',
        ),
    ]
