# Generated by Django 2.1 on 2018-11-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='heat',
            field=models.ManyToManyField(blank=True, related_name='user_heat', to='users.Profile'),
        ),
    ]
