# Generated by Django 2.1 on 2018-12-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20181210_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prevHeat',
            field=models.IntegerField(default=0),
        ),
    ]
