# Generated by Django 2.1.2 on 2018-12-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_newmatches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='adjectives',
            field=models.TextField(default='adjective', max_length=401),
        ),
    ]
