# Generated by Django 2.1 on 2018-12-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20181212_1818'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hobby',
            unique_together={('name',)},
        ),
    ]
