# Generated by Django 2.1.2 on 2018-11-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hobby',
        ),
    ]
